import type { Metadata, } from 'next'
import { Nunito_Sans as nunitoSans, } from 'next/font/google'
import './globals.css'

const mainFont = nunitoSans({ subsets: [ 'cyrillic', ], })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ mainFont.className }>{ children }</body>
    </html>
  )
}
